import { ToastContainer } from 'react-toastify'
import '../(payload)/custom.scss'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="w-screen h-screen">{children}</body>
      <ToastContainer autoClose={1000} position="top-center" />
    </html>
  )
}
